name: Javascript Release
on:
  pull_request:
    types:
      - closed

jobs:
  test:
    uses: ./.github/workflows/javascript_test.yml
  prepare:
    needs: ['test']
    name: Prepare release generation
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Generate release Matrix
        id: matrix
        env:
          PULL_LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: python ./.github/scripts/generate_release_matrix.py
  release:
    name: Generates Github Releases
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
          token: ${{ secrets.ARABOT_PAT }}
      - name: apply version Bump
        id: bump
        run: | 
          yarn version --${{ matrix.bump }} --no-git-tag-version
          VERSION=$(cat package.json | jq -r .version)
          echo "::set-output name=version::$VERSION"
        working-directory: 'javascript/modules/${{ matrix.package }}'
      - name: Commit new package version
        id: commit
        run: |
          git fetch
          git pull
          git config --global user.name "Arabot-1"
          git config --global user.email "arabot-1@users.noreply.github.com"
          git add ./javascript/modules/${{ matrix.package }}/package.json
          git commit -am "Updates version in package.json for ${{ matrix.package }}"
          git push
          echo "::set-output name=commitid::$(git rev-parse HEAD)"
      - name: create tag
        uses: actions/github-script@v5
        env:
          TAG_NAME: "${{ steps.bump.outputs.version }}-javascript-${{ matrix.package }}"
        with:
          github-token: ${{ secrets.ARABOT_PAT }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.TAG_NAME}`,
              sha: ${{ steps.commit.outputs.commitid }}
            })
